import Head from "next/head"
import { useRouter } from "next/router"
import { useState } from "react"
import styles from "../styles/Home.module.css"
import Link from "next/link"
import { FaArrowLeft } from "react-icons/fa"

const Blog = (props: any) => {
  const router = useRouter()
  const { bid } = router.query
  const [blogDetails, setBlogDetails] = useState(props.blogDetail)

  console.log(blogDetails, "blogDetails")

  return (
    <>
      <Head>
        <title>User Details</title>
        <meta name="description" content="Generated by Umair Saeed" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <h1 className="text-5xl text-center underline p-2.5">User Details</h1>

      {blogDetails && (
        <main className={styles.userDetails}>
          <p>
            <span className="w-40 inline-block">ID:</span>{" "}
            <span className="text-rose-900 text-2xl">{blogDetails.id}</span>
          </p>
          <p>
            <span className="w-40 inline-block">Name:</span>{" "}
            <span className="text-rose-900 text-2xl">{blogDetails.name}</span>
          </p>
          <p>
            <span className="w-40 inline-block">UserName:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails.username}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">Email: </span>
            <span className="text-rose-900 text-2xl">{blogDetails.email}</span>
          </p>
          <p>
            <span className="w-40 inline-block">Phone No.:</span>{" "}
            <span className="text-rose-900 text-2xl">{blogDetails.phone}</span>
          </p>
          <p>
            <span className="w-40 inline-block">Website:</span>{" "}
            <span className="text-rose-900 text-2xl">
              {blogDetails.website}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">Street No.:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails.address.street}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">Suite No.:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails?.address?.suite}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">City:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails?.address?.city}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">Zip Code:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails?.address?.zipcode}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">Latitude:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails?.address?.geo?.lat}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">Longitude:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails?.address?.geo?.lng}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">Company Name:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails?.company?.name}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">Catch Phrase:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails?.company?.catchPhrase}
            </span>
          </p>
          <p>
            <span className="w-40 inline-block">BS:</span>
            <span className="text-rose-900 text-2xl">
              {blogDetails?.company?.bs}
            </span>
          </p>
        </main>
      )}
      <Link href="/blogs" className="flex items-center justify-center m-2.5">
        <FaArrowLeft className="mr-1.5" />
        Back
      </Link>
    </>
  )
}

export async function getServerSideProps(context: any) {
  console.log(context, "Context")

  const { bid } = context.params
  const data = await fetch(`https://jsonplaceholder.typicode.com/users/${bid}`)
  const blogDetail = await data.json()
  return {
    props: { blogDetail },
  }
}

export default Blog
