import Head from "next/head"
import { useState } from "react"
import styles from "../styles/Home.module.css"
import Link from "next/link"
import { FaArrowLeft } from "react-icons/fa"

const User = (props: any) => {
  const [userDetails, setUserDetails] = useState(props.userDetail)

  return (
    <>
      <Head>
        <title>User Details</title>
        <meta name="description" content="Generated by Umair Saeed" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <h1 className="text-5xl text-center underline p-2.5 mt-24">
        User Details
      </h1>

      {userDetails && (
        <main className={styles.userDetails}>
          <p>
            <span className="w-40 sm:inline-block block">ID:</span>{" "}
            <span className="text-rose-900 text-2xl">{userDetails.id}</span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Name:</span>{" "}
            <span className="text-rose-900 text-2xl">{userDetails.name}</span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">UserName:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails.username}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Email: </span>
            <span className="text-rose-900 text-2xl">{userDetails.email}</span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Phone No.:</span>{" "}
            <span className="text-rose-900 text-2xl">{userDetails.phone}</span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Website:</span>{" "}
            <span className="text-rose-900 text-2xl">
              {userDetails.website}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Street No.:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails.address.street}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Suite No.:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails?.address?.suite}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">City:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails?.address?.city}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Zip Code:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails?.address?.zipcode}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Latitude:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails?.address?.geo?.lat}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Longitude:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails?.address?.geo?.lng}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Company Name:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails?.company?.name}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">Catch Phrase:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails?.company?.catchPhrase}
            </span>
          </p>
          <p>
            <span className="w-40 sm:inline-block block">BS:</span>
            <span className="text-rose-900 text-2xl">
              {userDetails?.company?.bs}
            </span>
          </p>
        </main>
      )}
      <Link href="/users" className="flex items-center justify-center m-2.5">
        <FaArrowLeft className="mr-1.5" />
        Back
      </Link>
    </>
  )
}

export async function getServerSideProps(context: any) {
  const { uid } = context.params
  const data = await fetch(`https://jsonplaceholder.typicode.com/users/${uid}`)
  const userDetail = await data.json()
  return {
    props: { userDetail },
  }
}

export default User
