import React, { useState } from "react"
import styles from "../styles/Home.module.css"
import Head from "next/head"
import Link from "next/link"

const Blogs = (props: any) => {
  const [blogs, setBlogs] = useState(props.allProps)

  return (
    <>
      <Head>
        <title>API Call</title>
        <meta name="description" content="Generated by Umair Saeed" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <div>
        <main className="font-bold text-3xl text-center underline p-2.5">
          Fake Users from JSONPlaceholder
        </main>
        <main className={styles.blogwrapper}>
          {blogs.map((blog: any) => {
            return (
              <Link className={styles.details} href={`/${blog.id}`}>
                <h2>{blog.id}</h2>
                <h3>{blog.name}</h3>
                <h4>{blog.username}</h4>
              </Link>
            )
          })}
        </main>
      </div>
    </>
  )
}

export async function getServerSideProps() {
  const data = await fetch("https://jsonplaceholder.typicode.com/users")
  const allProps = await data.json()

  return {
    props: { allProps },
  }
}

export default Blogs
