import React from "react"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import Link from "next/link"
import { Todo } from "../src/types/index"

interface TodosProps {
  allTodos: Todo[]
}

function Todos(props: TodosProps) {
  const { allTodos } = props

  return (
    <>
      <Head>
        <title>TODO Call</title>
        <meta name="description" content="Generated by Umair Saeed" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <div>
        <div>
          <main className="font-bold text-3xl text-center underline p-2.5 mt-24">
            Fake Todos from JSONPlaceholder
          </main>
        </div>
        <main className="flex flex-wrap cursor-pointer justify-center">
          {allTodos.map((todo) => {
            return (
              <Link className={styles.details} href={`/${todo.id}`}>
                <h2>{todo.id}</h2>
                <h3>{todo.userId}</h3>
                <h4 className="capitalize">{todo.title}</h4>
              </Link>
            )
          })}
        </main>
      </div>
    </>
  )
}

export async function getServerSideProps() {
  const data = await fetch("https://jsonplaceholder.typicode.com/todos")
  const allTodos = await data.json()

  return {
    props: { allTodos },
  }
}

export default Todos
